package com.reweb.browser.engine.webview

/**
 * Lets streaming sites work on devices whose Widevine module predates server
 * certificates.
 *
 * ## The problem
 *
 * Encrypted Media Extensions defines `MediaKeys.setServerCertificate()` as an
 * *optional* optimisation. A site provides the licence server's certificate so the
 * CDM can encrypt its client ID directly ("privacy mode"), saving a round trip.
 * The spec is explicit that a CDM which does not support server certificates
 * should resolve the call with `false`, after which the player falls back to the
 * ordinary individualization flow.
 *
 * Widevine modules from around 2014 predate that certificate format. Rather than
 * reporting that they cannot use it, they accept the call and then fail later,
 * inside key request generation:
 *
 * ```
 * E/WVCdm: CdmLicense::PrepareKeyRequest: retrieved certificate not of type service, 0
 * E/WVCdm: CdmEngine::GenerateKeyRequest: key request generation failed, sts = 3
 * ```
 *
 * The failure is local — before any network request — so the site never gets a
 * licence. A control on the same device isolates it: the DASH-IF reference
 * player, which never calls `setServerCertificate`, licenses successfully, while
 * Spotify, which does, fails at exactly that line.
 *
 * ## What this does
 *
 * On affected devices only, `setServerCertificate` is replaced with a function
 * that resolves `false` — the answer the spec already defines for a CDM without
 * server certificate support, and an honest description of this hardware.
 *
 * ## What this is not
 *
 * It does not weaken or bypass DRM. The licence request is still generated by the
 * CDM, still sent to the service's own licence server, still validated there, and
 * still requires whatever entitlement the account carries. Only the protection of
 * the client ID in transit changes, between two flows the spec already defines.
 *
 * It writes nothing to device state — unlike the provisioning repair this project
 * withdrew — so it is undone completely by uninstalling.
 *
 * ## What it does not achieve
 *
 * On the test device it removes the certificate error but does **not** produce
 * full Spotify playback; tracks still stop when the unencrypted lead-in ends. It
 * is kept because it corrects a real, reproducible protocol violation by the CDM,
 * not because it is known to make any particular site work.
 */
internal object LegacyCdmShim {

    /**
     * Widevine modules built before this year cannot parse a modern service
     * certificate. The device that motivated this reports a 2014 build; 2016 is a
     * deliberately conservative cut-off, and a capable CDM is never shimmed.
     */
    private const val LAST_AFFECTED_BUILD_YEAR = 2016

    fun isNeeded(drmBuildYear: Int?): Boolean =
        drmBuildYear != null && drmBuildYear <= LAST_AFFECTED_BUILD_YEAR

    /**
     * Replaces `setServerCertificate` with the spec's "not supported" answer.
     *
     * Injected at [android.webkit.WebViewClient.onPageStarted] rather than through
     * androidx.webkit's document-start API, which is `@RestrictTo` in the versions
     * that still support this project's minSdk. Page-start injection runs before a
     * player's initialisation code reaches EME, which is all this needs.
     *
     * Written defensively: if EME is absent, or the property cannot be redefined,
     * it does nothing rather than throwing into an unrelated page.
     */
    val SCRIPT: String = """
        (function () {
          try {
            if (typeof MediaKeys === 'undefined' || !MediaKeys.prototype) { return; }
            if (MediaKeys.prototype.__rewebLegacyCdm) { return; }
            var original = MediaKeys.prototype.setServerCertificate;
            if (typeof original !== 'function') { return; }
            // Resolving false is what EME defines for a CDM that does not support
            // server certificates, which accurately describes this device's
            // Widevine module. Compliant players then use individualization.
            MediaKeys.prototype.setServerCertificate = function () {
              return Promise.resolve(false);
            };
            MediaKeys.prototype.__rewebLegacyCdm = true;
          } catch (e) {
            // Never let a compatibility shim break an unrelated page.
          }
        })();
    """.trimIndent()
}
