package com.reweb.browser.engine.webview

import android.webkit.WebView
import androidx.webkit.WebViewCompat
import androidx.webkit.WebViewFeature

/**
 * Lets streaming sites work on devices whose Widevine module predates server
 * certificates.
 *
 * ## The problem
 *
 * Encrypted Media Extensions defines `MediaKeys.setServerCertificate()` as an
 * *optional* optimisation. A site provides the licence server's certificate so the
 * CDM can encrypt its client ID directly ("privacy mode"), saving a round trip.
 * The spec is explicit that a CDM which does not support server certificates
 * should resolve the call with `false`, after which the player falls back to the
 * ordinary individualization flow.
 *
 * Widevine modules from around 2014 predate that certificate format. Rather than
 * reporting that they cannot use it, they accept the call and then fail later,
 * inside key request generation:
 *
 * ```
 * E/WVCdm: CdmLicense::PrepareKeyRequest: retrieved certificate not of type service, 0
 * E/WVCdm: CdmEngine::GenerateKeyRequest: key request generation failed, sts = 3
 * ```
 *
 * The failure is local — it happens before any network request — so the site
 * simply never gets a licence. On a Samsung Galaxy J2 (Android 5.1.1,
 * `Level3 Library Dec 11 2014`) this is exactly what stops Spotify from playing,
 * while a player that never calls `setServerCertificate` licenses successfully on
 * the same device.
 *
 * ## What this does
 *
 * On affected devices only, `setServerCertificate` is replaced with a function
 * that resolves `false` — the answer the spec already defines for a CDM without
 * server certificate support, and an honest description of this hardware.
 * Players that follow the spec then use individualization, which these modules
 * handle correctly.
 *
 * ## What this is not
 *
 * It does not weaken or bypass DRM. The licence request is still generated by the
 * CDM, still sent to the service's own licence server, still validated there, and
 * still requires whatever entitlement the account carries. Nothing is decrypted
 * that the service did not authorise. The only thing that changes is whether the
 * client ID is protected by a pre-shared service certificate or by the
 * individualization exchange — both are standard, and the service chooses how to
 * respond.
 *
 * It is also not applied everywhere. Modern CDMs handle server certificates
 * perfectly well and benefit from the saved round trip, so the shim is installed
 * only where the platform's Widevine module is old enough to be affected.
 */
internal object LegacyCdmShim {

    /**
     * Widevine modules built before this year cannot parse a modern service
     * certificate. The device that motivated this reports a 2014 build; 2016 is a
     * deliberately conservative cut-off, and the shim is harmless where it is not
     * needed because a capable CDM is simply never asked.
     */
    private const val LAST_AFFECTED_BUILD_YEAR = 2016

    /**
     * Installs the shim if this device needs it and the WebView supports running a
     * script before page content. Returns true if it was installed.
     *
     * Document-start injection is required: the replacement has to be in place
     * before the page's player code captures a reference to the original.
     */
    fun installIfNeeded(webView: WebView, drmBuildYear: Int?): Boolean {
        if (drmBuildYear == null || drmBuildYear > LAST_AFFECTED_BUILD_YEAR) return false
        if (!WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT)) return false
        return runCatching {
            WebViewCompat.addDocumentStartJavaScript(webView, SCRIPT, setOf("*"))
            true
        }.getOrDefault(false)
    }

    /**
     * Replaces `setServerCertificate` with the spec's "not supported" answer.
     *
     * Written defensively: if EME is absent, or the property cannot be redefined,
     * the script does nothing rather than throwing into an unrelated page.
     */
    private val SCRIPT = """
        (function () {
          try {
            if (typeof MediaKeys === 'undefined' || !MediaKeys.prototype) { return; }
            if (MediaKeys.prototype.__rewebLegacyCdm) { return; }
            var original = MediaKeys.prototype.setServerCertificate;
            if (typeof original !== 'function') { return; }
            // Resolving false is what EME defines for a CDM that does not support
            // server certificates, which is an accurate description of the Widevine
            // module on this device. Compliant players then fall back to the
            // individualization flow, which it does support.
            MediaKeys.prototype.setServerCertificate = function () {
              return Promise.resolve(false);
            };
            MediaKeys.prototype.__rewebLegacyCdm = true;
          } catch (e) {
            // Never let a compatibility shim break an unrelated page.
          }
        })();
    """.trimIndent()
}
